GET http://localhost:5000/api/languages/1

###
PATCH http://localhost:5000/api/languages/1
Content-Type: application/json

{
    "shouldShowSpaces": "true"
}

###
POST http://localhost:5000/api/texts
Content-Type: application/json

{
    "languageId": 1,
    "title": "Test title",
    "content": "Test content",
    "sourceUrl": "example.com"
}

###
PATCH http://localhost:5000/api/texts/1
Content-Type: application/json

{
    "content": "Updated content",
    "sourceUrl": "example.com/updated"
}

###
GET http://localhost:5000/api/words/12

###
POST http://localhost:5000/api/words
Content-Type: application/json

{
    "languageId": 1,
    "content": "Test content",
    "status": "Test status",
    "entries":
    [
        {
            "meaning": "Test meaning",
            "reading": "Test reading"
        },
        {
            "meaning": "Test meaning 2",
            "reading": "Test reading 2"
        }
    ],
    "notes": "Test notes",
    "datetimeAdded": "2021-01-01T00:00:00",
    "datetimeUpdated": "2021-01-01T00:00:00"
}

###
PATCH http://localhost:5000/api/words/1
Content-Type: application/json

{
    "content": "Updated content",
    "status": "Updated status",
    "notes": "Updated notes",
    "entries":
    [
        {
            "meaning": "Updated meaning",
            "reading": "Updated reading"
        }
    ],
    "datetimeUpdated": "2021-01-05T00:00:00"
}

###
DELETE http://localhost:5000/api/words/1
